.build:
  stage: build
  tags:
  - k8s
  script:
  - ${BUILD_SHELL}

.build-docker:
  stage: buildimage
  tags:
  - build
  script:
  - sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWD  $CI_REGISTRY
  - sudo docker build -t ${IMAGE_NAME} -f ${DOCKER_FILE_PATH} .
  - sudo docker push ${IMAGE_NAME} 
  - sudo docker rmi ${IMAGE_NAME} 
