.build:
  stage: build
  tags:
  - k8s
  script:
  - ${BUILD_SHELL}

.build-docker:
  stage: buildimage
  tags:
  - k8s
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD  $CI_REGISTRY
  - docker build -t ${IMAGE_NAME} -f ${DOCKER_FILE_PATH} .
  - docker push ${IMAGE_NAME} 
  - docker rmi ${IMAGE_NAME} 
