include:
- project: "cidevops/cidevops-newci-service"
  ref: master
  file: "jobs/build.yml"
- project: "cidevops/cidevops-newci-service"
  ref: master
  file: "jobs/test.yml"
- project: "cidevops/cidevops-newci-service"
  ref: master
  file: "jobs/codeanalysis.yml"
- project: "cidevops/cidevops-newci-service"
  ref: master
  file: "jobs/deploy_kubernetes.yml"

variables:
  #全局配置
  GIT_CLONE_PATH: "$CI_BUILDS_DIR/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_PIPELINE_ID"
  GIT_CHECKOUT: "false"
  
  #依赖的容器镜像
  BUILD_IMAGE: "maven:3.6.3-jdk-8"
  SONAR_IMAGE: "sonarsource/sonar-scanner-cli:latest"
  KUBECTL_IMAGE: "lucj/kubectl:1.17.2"
  
  #构建测试参数
  MAVEN_OPTS: "-Dmaven.repo.local=/home/gitlab-runner/ci-build-cache/maven"
  BUILD_SHELL: "mvn clean package -DskipTests --settings=./settings.xml"
  TEST_SHELL: "mvn test --settings=./settings.xml"
  JUNIT_REPORT_PATH: "target/surefire-reports/TEST-*.xml"
  
  #代码扫描相关变量
  SONAR_SERVER: "http://sonarqubetest.goschainccap.com"
  SONAR_USER: "admin"
  SONAR_USER_PASSWORD: "admin"
  SONAR_PROJECT_LANG: "JAVA"
  SONAR_SOURCE_DIR: "src"
  SONAR_SCAN_ARGS: "-Dsonar.sources=${SONAR_SOURCE_DIR} 
                   -Dsonar.java.binaries=target/classes 
                   -Dsonar.java.test.binaries=target/test-classes"  

  #构建镜像相关变量
  CI_REGISTRY: "registry.cn-beijing.aliyuncs.com"
  IMAGE_NAME: "$CI_REGISTRY/goschain/$CI_PROJECT_NAMESPACE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
  DOCKER_FILE_PATH: "./Dockerfile"
  
  #部署到k8s相关变量
  RUN_DEPLOY_K8S: "yes"
  NAMESPACE: "$CI_PROJECT_NAMESPACE"
  APP_NAME: "$CI_PROJECT_NAME"
  CONTAINER_PORT: 8081
  NODE_PORT: 30184
  ENV_NAME: "staging"
  
cache:
  paths:
  - target/

#流水线控制，当创建分支时不触发流水线
workflow:
  rules:
  - if: $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"
    when: never
  - when: always

stages:
- build
- test
- parallel01
- deploy
- rollout

build:
  stage: build
  variables:
    GIT_CHECKOUT: "true"
  image: ${BUILD_IMAGE}
  extends: .build
  after_script:
  - ls target

test:
  stage: test
  image: ${BUILD_IMAGE}
  extends: .test
  before_script:
  - pwd
  - ls
  - ls target/
  
cod_analysis:
  stage: parallel01
  image: ${SONAR_IMAGE}
  extends: .code_analysis

build_image:
  stage: parallel01
  image: docker:latest
  extends: .build-docker

deploy_k8s:
  stage: deploy
  image: ${KUBECTL_IMAGE}
  extends: .deploy_k8s

rollout_k8s:
  stage: rollout
  image: ${KUBECTL_IMAGE}
  extends: .rollout_k8s 
