include:
- project: "cidevops/cidevops-newci-service"
  ref: master
  file: "jobs/build.yml"

  
stages:
- build

build:
  variables:
    GIT_CHECKOUT: "true"
  image: "${BUILD_IMAGE}"
  extends: .build